Here we demo the use of a function to randomly generate motion from a synthetic dataset

In [1]:
import nibabel as nb
import numpy as np

Read in the series:

In [38]:
path = '/Users/ttapera/Documents/BBL/Projects/motion_simulation/'
nomotion = path + 'data/realistic/nomotion/sub-ABCD/dwi/sub-ABCD_acq-realistic_run-nomotion_dwi.nii.gz'
motion = path + 'data/realistic/lowmotion/sub-ABCD/dwi/sub-ABCD_acq-realistic_run-lowmotion_dwi.nii.gz'

In [14]:
x_nomotion = nb.load(nomotion)
x_nomotion

In [16]:
x_lowmotion = nb.load(motion)
x_lowmotion

Extract data from niftis into arrays:

In [17]:
arr_nomotion = x_nomotion.get_fdata()
arr_lowmotion = x_lowmotion.get_fdata()

From the series of low motion, we want to sample 10% of the volumes, and replace volumes in no-motion with this 10%, at the corresponding indeces.

In [18]:
arr_nomotion.shape

(90, 108, 90, 103)

In [19]:
n_vols = arr_nomotion.shape[-1]

In [22]:
# two volumes are same shape
assert n_vols == arr_lowmotion.shape[-1]

In [25]:
prop = 0.1 # 10% proportion

# sample from [0-n_vols), a proportion of the volumes
np.random.randint(n_vols, size=round(prop*n_vols))

array([93, 37, 32, 97, 88, 99, 30,  9, 17, 90])

Here's one of the volumes to be replaced:

In [30]:
to_replace = np.random.randint(n_vols, size=round(prop*n_vols))

arr_nomotion[..., to_replace[0]]

array([[[20., 20.,  9., ...,  9., 16., 20.],
        [20., 22.,  7., ..., 23., 12., 20.],
        [26., 33., 14., ..., 10., 14., 29.],
        ...,
        [16., 11., 20., ..., 10.,  7., 34.],
        [ 6., 18., 13., ...,  8., 24.,  9.],
        [ 6., 11., 21., ..., 12., 15., 13.]],

       [[13., 23.,  9., ..., 22., 47., 14.],
        [37., 18., 29., ..., 23., 17., 16.],
        [12., 16., 14., ..., 29., 18., 17.],
        ...,
        [20., 46., 26., ..., 27., 38., 18.],
        [ 1., 27., 11., ..., 17., 27., 14.],
        [16., 24., 15., ...,  3., 27., 14.]],

       [[21., 16., 39., ...,  3., 18., 28.],
        [16., 26., 15., ..., 18., 42., 10.],
        [36., 43., 21., ..., 18., 33.,  7.],
        ...,
        [17., 31., 17., ...,  8., 19., 25.],
        [ 5., 20., 15., ..., 17., 26., 10.],
        [25., 23., 30., ..., 29., 19., 23.]],

       ...,

       [[21., 14., 32., ..., 20.,  7.,  8.],
        [10., 25., 10., ..., 19., 25., 19.],
        [26.,  7., 17., ...,  6., 25., 12.

And here is it's eventual replacement:

In [31]:
arr_lowmotion[..., to_replace[0]]

array([[[ 7., 21., 34., ..., 43., 28., 17.],
        [11., 16., 10., ..., 11., 31., 44.],
        [ 5., 16., 16., ..., 28., 35., 17.],
        ...,
        [26., 25., 15., ..., 24., 16., 14.],
        [ 4., 19., 57., ..., 18., 24., 31.],
        [14.,  7., 13., ..., 19., 17., 11.]],

       [[32.,  5., 12., ..., 21., 20.,  8.],
        [10., 12., 25., ..., 19.,  8., 22.],
        [ 9., 21., 10., ..., 23., 30., 26.],
        ...,
        [11., 16., 11., ..., 11., 16., 41.],
        [16.,  6., 12., ..., 11., 24.,  7.],
        [40., 23., 45., ..., 31., 11., 34.]],

       [[30.,  8., 14., ..., 43., 14., 21.],
        [12., 18., 37., ..., 37., 17., 27.],
        [25., 11., 12., ..., 28., 18.,  9.],
        ...,
        [15., 17., 48., ...,  9., 49., 18.],
        [32., 16., 14., ..., 27., 22.,  4.],
        [24., 15., 14., ..., 30., 38., 22.]],

       ...,

       [[30., 20.,  4., ...,  7.,  9., 43.],
        [16.,  6., 15., ..., 16., 15., 11.],
        [13.,  7., 26., ..., 21., 36., 25.

Replacement is straightforward:

In [34]:
output = arr_nomotion.copy()
output[...,to_replace] = arr_lowmotion[..., to_replace]

In [35]:
output[...,to_replace[0]]

array([[[ 7., 21., 34., ..., 43., 28., 17.],
        [11., 16., 10., ..., 11., 31., 44.],
        [ 5., 16., 16., ..., 28., 35., 17.],
        ...,
        [26., 25., 15., ..., 24., 16., 14.],
        [ 4., 19., 57., ..., 18., 24., 31.],
        [14.,  7., 13., ..., 19., 17., 11.]],

       [[32.,  5., 12., ..., 21., 20.,  8.],
        [10., 12., 25., ..., 19.,  8., 22.],
        [ 9., 21., 10., ..., 23., 30., 26.],
        ...,
        [11., 16., 11., ..., 11., 16., 41.],
        [16.,  6., 12., ..., 11., 24.,  7.],
        [40., 23., 45., ..., 31., 11., 34.]],

       [[30.,  8., 14., ..., 43., 14., 21.],
        [12., 18., 37., ..., 37., 17., 27.],
        [25., 11., 12., ..., 28., 18.,  9.],
        ...,
        [15., 17., 48., ...,  9., 49., 18.],
        [32., 16., 14., ..., 27., 22.,  4.],
        [24., 15., 14., ..., 30., 38., 22.]],

       ...,

       [[30., 20.,  4., ...,  7.,  9., 43.],
        [16.,  6., 15., ..., 16., 15., 11.],
        [13.,  7., 26., ..., 21., 36., 25.

Then we write out to file:

In [39]:
nb.Nifti1Image(output, x_nomotion.affine, header=x_nomotion.header).to_filename(path + "output/asdf.nii.gz")

Let's write a function!

In [43]:
def simulate_motion(input_nomotion, input_motion, proportion):
    
    input_nomotion = nb.load(input_nomotion)
    input_motion = nb.load(input_motion)
    nomotion_arr = input_nomotion.get_fdata()
    motion_arr = input_motion.get_fdata()
    assert motion_arr.shape[-1] == nomotion_arr.shape[-1]

    n_vols = nomotion_arr.shape[-1]
    to_replace = np.random.randint(n_vols, size=round(proportion*n_vols))
    
    out = nomotion_arr.copy()
    out[...,to_replace] = motion_arr[..., to_replace]
    out = nb.Nifti1Image(out, input_nomotion.affine, header=input_nomotion.header)
    return out

In [44]:
result = simulate_motion(nomotion, motion, 0.1)

In [45]:
result